[[d1_databases]]
binding = "kathyayani_botitque"
database_name = "kathyayani-botitque"
database_id = "c1e6be51-b473-46d7-a6ce-56643a9edafa"
preview_database_id = "c1e6be51-b473-46d7-a6ce-56643a9edafa"
